name: morgan
version: 1.0.0
config-version: 2

profile: morgan

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

target-path: target
clean-targets:
  - target
  - dbt_packages

vars:
  lookback_days: 90

models:
  morgan:
    staging:
      +schema: silver
      +materialized: view
      +tags: ["silver"]
    marts:
      +schema: gold
      +materialized: table
      +tags: ["gold"]
